name: Run eo-ip every 10 minutes
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run eo-ip.py
        run: |
          # 安装依赖（如果需要）
          pip install ipaddress
          # 运行脚本
          python eo-ip.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add success_ips.txt failed_ips.txt
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update IP lists"
            git push
          fi
